### PR TITLE
Fixed Signup Screen Validation Bug

### LINKED ISSUE #144: Buggy Validation Errors on Signup Screen
# Problem 
image
In this case, the first and last name field is incorrect (b/c they need to start with a capital letter), but every other validation error also pops up. As a user this means I have no idea what I actually did wrong and it looks like the app is broken somehow, even though it's just a validation issue.

## More details
Clicking the create account button again results in the same behaviour where the validation errors simply repeat themselves. If I fix the validation error by fixing the first and last name inputs the create account button seems to work properly.

### PR DESCRIPTION
**Pull request by portoaj**
### Adminstrative Info

Closes #144 

### Changes

Made small changes to the validation logic to make sure every validation is always run so accurate validation errors are shown

### Testing

image

Validation works on the same example I first tried, in this case it only shows a validation error for the field that has the error, instead of all of them.

### CODE REVIEW

File: LAKMobile/src/screens/SignupScreen.tsx [hunk 1]
```diff
@@ -76,13 +76,13 @@ export function SignupScreen({ navigation }: SignupProps) {
...
-      validatePin() &&
-      validateConfirmPin()
-    ) {
+    validateName();
+    validatePhone();
+    validateLocation();
+    validatePin();
+    validateConfirmPin();
+
+    if (nameValid && phoneValid && locationValid && PINValid && confirmPINValid) {
```
Comment (alexzhang1618) [inline LAKMobile/src/screens/SignupScreen.tsx:85]: Good catch on the bug! I have a comment here:
Since setState doesn't update the state immediately after it's called  (there can sometimes be a little bit of lag), when we move to the if statement to check if the fields are valid, it might return false when we don't want it to. Instead, what we can do is read in the values returned by each of the validation functions and use those for our checking if flow since we can guarantee that the return values are the current return values

**Review by alexzhang1618 — CHANGES_REQUESTED** [review]

**Review by nbpillai — APPROVED** [review]
lgtm

**Review by alexzhang1618 — APPROVED** [review]
Brilliant 🤩
